// Sample data for the prototype
window.APP_DATA = {
  user: {
    name: "高田 和夫",
    initial: "和",
    region: "ギフト県のみ市",
    regions: ["のみ市", "きせ市"],
    organizingCount: 2,
    upcomingRegistered: 3,
    attended: 12,
  },

  regions: ["のみ市", "きせ市", "うじょぐ市", "ギフト市", "にか市", "みじた市", "かみはら市"],

  series: [
    {
      id: "ninchisho-cafe",
      name: "認知症カフェ in のみ",
      mark: "認",
      organizer: "のみ地域包括支援センター",
      desc: "認知症のご本人やご家族、支援者、地域の皆さまが気軽に集まれる場所です。毎月第2金曜の午後、コーヒーとお茶菓子を囲みながら、ゆっくりお話ししましょう。",
      startedYear: 2022,
      eventsCount: 18,
      totalAttendees: 326,
    },
    {
      id: "soup-time",
      name: "スープのタイム",
      mark: "湯",
      organizer: "高田 和夫",
      venue: "かがやくイス",
      desc: "仕事や育児の合間、ふっと立ち寄れる場所。毎月第3金曜日、季節のスープを一杯ご用意しています。高田和夫が一人で切り盛りする小さなカフェで、気軽にどうぞ。",
      startedYear: 2025,
      eventsCount: 11,
      totalAttendees: 178,
    },
  ],

  events: [
    {
      id: "e-001",
      seriesId: "ninchisho-cafe",
      title: "認知症カフェ in のみ — 第十八回",
      subtitle: "秋のおしゃべり会",
      date: "2026-05-08",
      dateLabel: "05.08",
      weekday: "金",
      time: "13:30 – 15:30",
      venue: "つだうの町家カフェ",
      address: "ギフト県のみ市本町2-14",
      region: "のみ市",
      lat: 54,
      lng: 38,
      organizer: "のみ地域包括支援センター",
      capacity: 20,
      registered: 14,
      price: "参加費 500円（お茶菓子付き）",
      tags: ["福祉", "定例", "のみ市"],
      summary: "認知症のご本人・ご家族・関心のある方、どなたでも。お茶を飲みながら、近況や悩みをゆっくり語り合いましょう。専門職のスタッフも同席します。",
      body: "つだうの町家のしっとりした空間で、地域の皆さまと語らう午後のひとときを。初めての方には、スタッフがご案内いたします。手ぶらでお気軽にお越しください。",
      featured: true,
      views: 342,
      photos: [],
      reports: [],
    },
    {
      id: "e-002",
      seriesId: "soup-time",
      title: "スープのタイム 〈 五月 〉",
      subtitle: "新玉ねぎと豆のミネストローネ",
      date: "2026-05-15",
      dateLabel: "05.15",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      lat: 48,
      lng: 52,
      organizer: "高田 和夫",
      capacity: 12,
      registered: 7,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "今月は春の新玉ねぎをコトコト煮込んだミネストローネ。ひと休のみ時間を、温かい一杯とともに。",
      body: "カウンター5席＋テーブル7席の小さなお店です。お一人様歓迎。ご予約なしでもお越しいただけますが、登録いただけると席をお取りしておきます。",
      views: 128,
      photos: [],
      reports: [],
    },
    {
      id: "e-002b",
      seriesId: "soup-time",
      title: "スープのタイム 〈 六月 〉",
      subtitle: "トマトと夏野菜のガスパチョ",
      date: "2026-06-19",
      dateLabel: "06.19",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      lat: 48,
      lng: 52,
      organizer: "高田 和夫",
      capacity: 12,
      registered: 3,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "夏のはじまり、冷たいガスパチョを。完熟トマトと夏野菜をたっぷり使った一杯です。",
      body: "カウンター5席＋テーブル7席の小さなお店です。お一人様歓迎。",
      views: 87,
      photos: [],
      reports: [],
    },
    {
      id: "e-002c",
      seriesId: "soup-time",
      title: "スープのタイム 〈 七月 〉",
      subtitle: "とうもろこしのポタージュ",
      date: "2026-07-17",
      dateLabel: "07.17",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      lat: 48,
      lng: 52,
      organizer: "高田 和夫",
      capacity: 12,
      registered: 1,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "旬のとうもろこしをじっくり煮出した、甘くてやさしいポタージュ。",
      body: "カウンター5席＋テーブル7席の小さなお店です。お一人様歓迎。",
      views: 203,
      photos: [],
      reports: [],
    },
    {
      id: "e-002d",
      seriesId: "soup-time",
      title: "スープのタイム 〈 八月 〉",
      subtitle: "冷製クレソンのスープ",
      date: "2026-08-21",
      dateLabel: "08.21",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      lat: 48,
      lng: 52,
      organizer: "高田 和夫",
      capacity: 12,
      registered: 0,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "真夏に飲みたい、きりっと冷たいクレソンのスープ。さわやかな苦みが暑さを和らげます。",
      body: "カウンター5席＋テーブル7席の小さなお店です。お一人様歓迎。",
      views: 456,
      photos: [],
      reports: [],
    },
    {
      id: "e-003",
      seriesId: "ninchisho-cafe",
      title: "みんなの回想ノートづくり",
      subtitle: "特別会 — 家族写真を持ちよって",
      date: "2026-05-22",
      dateLabel: "05.22",
      weekday: "金",
      time: "14:00 – 16:00",
      venue: "のみ和紙の里会館 多目的室",
      address: "ギフト県のみ市びらわ1851-3",
      region: "のみ市",
      lat: 30,
      lng: 22,
      organizer: "のみ地域包括支援センター",
      capacity: 16,
      registered: 11,
      price: "参加費 800円（材料費込み）",
      tags: ["福祉", "ワークショップ"],
      summary: "家族写真や懐かしい品を持ちよって、小さな回想ノートを作ります。のみ和紙を使った手作りの表紙付き。",
      views: 91,
      photos: [],
      reports: [],
    },
    {
      id: "e-004",
      seriesId: null,
      title: "古本とコーヒー、五月の読書会",
      subtitle: "課題図書『料理と呼吸』",
      date: "2026-05-17",
      dateLabel: "05.17",
      weekday: "日",
      time: "10:00 – 12:00",
      venue: "古書室 ツダウ",
      address: "ギフト県のみ市やじか町",
      region: "のみ市",
      lat: 62,
      lng: 46,
      organizer: "ツダウ読書会",
      capacity: 8,
      registered: 5,
      price: "参加費 1,000円（ドリンク付き）",
      tags: ["読書", "定例"],
      summary: "今月の課題図書は『料理と呼吸』。感想文不要、手ぶらで参加OK。静かに語り合う会です。",
      views: 67,
      photos: [],
      reports: [],
    },
    {
      id: "e-005",
      seriesId: null,
      title: "こども食堂 のみっこ",
      subtitle: "初夏のちらし寿司の会",
      date: "2026-05-10",
      dateLabel: "05.10",
      weekday: "日",
      time: "11:00 – 13:00",
      venue: "のみ公民館 調理室",
      address: "ギフト県のみ市みずい町1-21",
      region: "のみ市",
      lat: 44,
      lng: 30,
      organizer: "のみっこの会",
      capacity: 40,
      registered: 28,
      price: "こども無料 / 大人 300円",
      tags: ["こども", "食"],
      summary: "みんなで作って、みんなで食べる。小さなお子さんから高齢者まで、どなたでも。",
      views: 38,
      photos: [],
      reports: [],
    },
    {
      id: "e-006",
      seriesId: null,
      title: "まちのピアノ発表会 vol.3",
      subtitle: "だれでも3分、弾いていい",
      date: "2026-05-24",
      dateLabel: "05.24",
      weekday: "日",
      time: "14:00 – 17:00",
      venue: "旧西家住宅・蔵",
      address: "ギフト県のみ市みずい町1901",
      region: "のみ市",
      lat: 58,
      lng: 26,
      organizer: "まちのピアノ実行委員会",
      capacity: 30,
      registered: 19,
      price: "観覧無料 / 演奏者500円",
      tags: ["音楽", "イベント"],
      summary: "古い蔵に置かれたアップライトピアノ。3分だけ、誰でも弾いて、誰でも聴きにきていい。",
      views: 342,
      photos: [],
      reports: [],
    },
    {
      id: "e-008",
      seriesId: null,
      title: "はじめてのオンライン認知症相談会",
      subtitle: "Zoomで気軽に相談できる",
      date: "2026-05-28",
      dateLabel: "05.28",
      weekday: "木",
      time: "19:00 – 20:30",
      venue: "オンライン",
      address: "",
      online: true,
      onlineUrl: "https://zoom.us/j/00000000000",
      onlineNote: "参加登録後、前日にURLをメールでお送りします",
      region: "のみ市",
      lat: 50,
      lng: 50,
      organizer: "のみ地域包括支援センター",
      capacity: 30,
      registered: 8,
      price: "無料",
      tags: ["福祉", "オンライン"],
      summary: "外出が難しい方もご自宅から気軽にご参加いただけます。認知症に関する疑問や不安を、専門スタッフにオンラインでご相談いただける場です。",
      body: "パソコン・スマートフォン・タブレットからご参加いただけます。Zoomの操作が不安な方は事前にご連絡ください。",
      views: 128,
      photos: [],
      reports: [],
    },
    {
      id: "e-007",
      seriesId: null,
      title: "関の刃物市と朝コーヒー",
      subtitle: "五月の朝市",
      date: "2026-05-18",
      dateLabel: "05.18",
      weekday: "月",
      time: "07:00 – 10:00",
      venue: "関鍛冶伝承館 前広場",
      address: "ギフト県きせ市南がすか町9-1",
      region: "きせ市",
      lat: 36,
      lng: 68,
      organizer: "関のあさ市",
      capacity: 60,
      registered: 22,
      price: "入場無料",
      tags: ["朝市", "きせ市"],
      summary: "朝どれの野菜と、淹れたてのコーヒーと、刃物を眺める朝。",
      views: 87,
      photos: [],
      reports: [],
    },
  ],

  // Past events — these have reports and represent "already happened" entries
  pastEvents: [
    {
      id: "p-001",
      seriesId: "ninchisho-cafe",
      title: "認知症カフェ in のみ — 第十七回",
      subtitle: "花見のおしゃべり会",
      date: "2026-04-10",
      dateLabel: "2026.04.10",
      weekday: "金",
      time: "13:30 – 15:30",
      venue: "つだうの町家カフェ",
      address: "ギフト県のみ市本町2-14",
      region: "のみ市",
      organizer: "のみ地域包括支援センター",
      views: 248,
      attended: 17,
      capacity: 20,
      registered: 17,
      price: "参加費 500円（お茶菓子付き）",
      tags: ["福祉", "定例"],
      summary: "桜の季節の、やわらかな午後の会。",
      body: "毎月第2金曜の定例会。ご本人とご家族、地域の方々が、ゆっくり語り合う時間です。",
      reports: [
        {
          id: "r-001a",
          author: "事務局 山本",
          date: "2026-04-12",
          photos: 3,
          text: "桜の時期、17名の方にお集まりいただきました。今回は初めてご参加のご家族が4組。お茶菓子は近所の和菓子屋さんの桜餅で、お花見気分の会となりました。次回は5月8日、通常どおり「つだうの町家カフェ」にて。",
        },
        {
          id: "r-001b",
          author: "包括支援センター 河合",
          date: "2026-04-14",
          photos: 2,
          text: "ご質問の多かった「認知症初期の受診のタイミング」について、次回ミニコーナーとしてお話しする予定です。ご家族からのお悩みにお答えする形で、短く、やさしく。",
        },
      ],
    },
    {
      id: "p-soup-1",
      seriesId: "soup-time",
      title: "スープのタイム 〈 十一月 〉",
      subtitle: "かぼちゃのポタージュ",
      date: "2025-11-21",
      dateLabel: "2025.11.21",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      organizer: "高田 和夫",
      views: 365,
      attended: 10,
      capacity: 12,
      registered: 10,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "秋の定番、かぼちゃのポタージュ。",
      reports: [{ id: "rs-1", author: "高田 和夫", date: "2025-11-23", photos: 2, text: "初回から10名満席、ありがとうございました。かぼちゃは地元農家さんから仕入れた栗かぼちゃを使いました。" }],
    },
    {
      id: "p-soup-2",
      seriesId: "soup-time",
      title: "スープのタイム 〈 十二月 〉",
      subtitle: "根菜のポトフ",
      date: "2025-12-19",
      dateLabel: "2025.12.19",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      organizer: "高田 和夫",
      views: 186,
      attended: 11,
      capacity: 12,
      registered: 12,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "冬野菜をじっくり煮込んだポトフ。",
      reports: [{ id: "rs-2", author: "高田 和夫", date: "2025-12-21", photos: 3, text: "年末の忙しい時期にほっとしに来てくれた方が多かったです。根菜のやさしい甘みが好評でした。" }],
    },
    {
      id: "p-soup-3",
      seriesId: "soup-time",
      title: "スープのタイム 〈 一月 〉",
      subtitle: "豚汁風みそスープ",
      date: "2026-01-16",
      dateLabel: "2026.01.16",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      organizer: "高田 和夫",
      views: 301,
      attended: 9,
      capacity: 12,
      registered: 9,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "新年最初は豚汁風のみそスープ。",
      reports: [{ id: "rs-3", author: "高田 和夫", date: "2026-01-18", photos: 2, text: "新年最初の会。みそベースで豚肉と根菜たっぷり。寒い日にぴったりでした。今年もよろしくお願いします。" }],
    },
    {
      id: "p-soup-4",
      seriesId: "soup-time",
      title: "スープのタイム 〈 二月 〉",
      subtitle: "白菜とベーコンのクリームスープ",
      date: "2026-02-20",
      dateLabel: "2026.02.20",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      organizer: "高田 和夫",
      views: 217,
      attended: 10,
      capacity: 12,
      registered: 10,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "白菜とベーコンを生クリームで仕上げたリッチなスープ。",
      reports: [{ id: "rs-4", author: "高田 和夫", date: "2026-02-22", photos: 2, text: "今月は白菜のとろとろクリームスープ。リピーターさんから「今までで一番好き」との声をいただきました。" }],
    },
    {
      id: "p-soup-5",
      seriesId: "soup-time",
      title: "スープのタイム 〈 三月 〉",
      subtitle: "春キャベツと豆のミネストローネ",
      date: "2026-03-20",
      dateLabel: "2026.03.20",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      organizer: "高田 和夫",
      views: 283,
      attended: 11,
      capacity: 12,
      registered: 11,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "春キャベツと豆のミネストローネ、季節の変わり目に。",
      reports: [{ id: "rs-5", author: "高田 和夫", date: "2026-03-22", photos: 3, text: "春らしい青みが出てきたミネストローネ。春キャベツの甘みがよく出ていました。次回はレシピカードをお配りします。" }],
    },
    {
      id: "p-005",
      seriesId: "soup-time",
      title: "スープのタイム 〈 四月 〉",
      subtitle: "春野菜でかろやかレシピ",
      date: "2026-04-17",
      dateLabel: "2026.04.17",
      weekday: "金",
      time: "11:30 – 14:00",
      venue: "かがやくイス",
      address: "ギフト県のみ市おかひろ町1-8",
      region: "のみ市",
      organizer: "高田 和夫",
      views: 369,
      attended: 11,
      capacity: 12,
      registered: 12,
      price: "スープ一杯 700円",
      tags: ["食", "定例"],
      summary: "新玉ねぎと菜の花の、春のやさしい会。",
      reports: [
        {
          id: "r-005a",
          author: "かがやくイス 中野",
          date: "2026-04-18",
          photos: 3,
          text: "4月のスープのタイムは、常連さん7名・はじめましての方4名、計11名にお越しいただきました。今月のメイン「新玉ねぎのポタージュ」は、おかわりが3杯出たのが嬉しかったです。以下、お渡ししたレシピです。ご家庭でもぜひ。",
          handoutTitle: "スープのタイム 4月",
          handoutSubtitle: "春野菜でかろやかレシピ",
          handoutTagline: "家にある材料でササっと作れる簡単レシピ",
          nutritionPerServing: [
            { k: "エネルギー", v: "420", u: "kcal" },
            { k: "タンパク質", v: "14.2", u: "g" },
            { k: "脂質", v: "11.8", u: "g" },
            { k: "炭水化物", v: "62.4", u: "g" },
          ],
          sides: ["春キャベツのコールスロー", "ディルと新じゃがのサラダ", "いちごのマリネ"],
          recipes: [
            {
              id: "rec-1",
              name: "新玉ねぎのポタージュ",
              serves: "4人分",
              ingredients: [
                "新玉ねぎ  3個", "じゃがいも  1個",
                "だし汁  400ml", "牛乳  200ml",
                "バター  10g", "塩・こしょう  少々",
                "パセリ（飾り用）",
              ],
              steps: [
                "鍋にバターを溶かし、薄切りにした新玉ねぎとじゃがいもを加え中火で炒める。だし汁を加え、野菜が柔らかくなるまで煮る。",
                "火を止め、ハンドブレンダーで滑らかにし、牛乳を加え塩・こしょうで味を整える。",
              ],
            },
            {
              id: "rec-2",
              name: "菜の花の炊き込みごはん",
              serves: "4人分",
              ingredients: [
                "米  2合", "菜の花  1/2束",
                "油揚げ  1枚", "酒  大さじ1",
                "塩  小さじ1/2", "白ごま  少々",
              ],
              steps: [
                "米を洗い、酒と塩を加えて通常の水加減で炊飯する。",
                "菜の花はさっと茹で、1cmに刻む。油揚げは細切りに。",
                "炊き上がったごはんに、菜の花と油揚げを混ぜ、白ごまをふる。",
              ],
            },
            {
              id: "rec-3",
              name: "豚肉の青じそ巻き",
              serves: "4人分",
              ingredients: [
                "豚薄切り肉  200g", "青じそ  8枚",
                "小麦粉・塩こしょう  少々", "オリーブオイル",
                "みりん  大さじ2", "醤油  大さじ2",
              ],
              steps: [
                "豚肉に塩・こしょう、小麦粉をふり、青じそをのせて巻く。",
                "フライパンにオリーブオイルを熱し、豚肉に焼き色を付ける。",
                "みりん・醤油を加え、煮からめて照りを出す。",
              ],
            },
          ],
        },
      ],
    },
    {
      id: "p-002",
      seriesId: "ninchisho-cafe",
      title: "認知症カフェ in のみ — 第十六回",
      subtitle: "春のはじまり",
      date: "2026-03-13",
      dateLabel: "2026.03.13",
      weekday: "金",
      time: "13:30 – 15:30",
      venue: "つだうの町家カフェ",
      address: "ギフト県のみ市本町2-14",
      region: "のみ市",
      organizer: "のみ地域包括支援センター",
      views: 265,
      attended: 14,
      capacity: 20,
      registered: 14,
      price: "参加費 500円（お茶菓子付き）",
      tags: ["福祉", "定例"],
      summary: "保健師さんのミニ講座を行いました。",
      reports: [
        {
          id: "r-002a",
          author: "事務局 山本",
          date: "2026-03-15",
          photos: 4,
          text: "今月は、地域包括の保健師さんによるミニ講座「家族の変化に気づいたら」を開催。ご質問が多く、時間を延長しての会となりました。参加者同士が連絡先を交換される場面も。",
        },
      ],
    },
    {
      id: "p-003",
      seriesId: "ninchisho-cafe",
      title: "認知症カフェ in のみ — 第十五回",
      subtitle: "二月の会",
      date: "2026-02-14",
      dateLabel: "2026.02.14",
      weekday: "金",
      time: "13:30 – 15:30",
      venue: "つだうの町家カフェ",
      address: "ギフト県のみ市本町2-14",
      region: "のみ市",
      organizer: "のみ地域包括支援センター",
      views: 115,
      attended: 12,
      capacity: 20,
      registered: 12,
      price: "参加費 500円（お茶菓子付き）",
      tags: ["福祉", "定例"],
      summary: "寒い日の、甘酒と梅干しの会。",
      reports: [
        {
          id: "r-003a",
          author: "事務局 山本",
          date: "2026-02-16",
          photos: 3,
          text: "寒い日の午後、12名に。温かい甘酒をお出ししました。参加者の方が手作りの梅干しを差し入れてくださって、ほっこりとした時間でした。",
        },
      ],
    },
    {
      id: "p-004",
      seriesId: "ninchisho-cafe",
      title: "認知症カフェ in のみ — 第十四回",
      subtitle: "新年のごあいさつ",
      date: "2026-01-09",
      dateLabel: "2026.01.09",
      weekday: "金",
      time: "13:30 – 15:30",
      venue: "つだうの町家カフェ",
      address: "ギフト県のみ市本町2-14",
      region: "のみ市",
      organizer: "のみ地域包括支援センター",
      views: 189,
      attended: 15,
      capacity: 20,
      registered: 15,
      price: "参加費 500円（お茶菓子付き）",
      tags: ["福祉", "定例"],
      summary: "今年もよろしくお願いします。",
      reports: [
        {
          id: "r-004a",
          author: "事務局 山本",
          date: "2026-01-11",
          photos: 2,
          text: "新年最初の会。今年も月に一度、ゆっくり集まれる場を続けていきます。お正月の飾りをみんなで片付けながらのスタートでした。",
        },
      ],
    },
  ],
};
